-- 1. CRÉATION ET SÉLECTION DE LA BASE DE DONNÉES
CREATE DATABASE IF NOT EXISTS mercato_nova CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mercato_nova;

-- 2. NETTOYAGE DES TABLES (Dans le bon ordre pour éviter les conflits de clés étrangères)
DROP TABLE IF EXISTS MESSAGE_NEGO;
DROP TABLE IF EXISTS OFFRE;
DROP TABLE IF EXISTS CONTIENT;
DROP TABLE IF EXISTS NEGOCIATION;
DROP TABLE IF EXISTS ENCHERE;
DROP TABLE IF EXISTS COMMANDE;
DROP TABLE IF EXISTS PRODUIT;
DROP TABLE IF EXISTS CATEGORIE;
DROP TABLE IF EXISTS UTILISATEUR;

-- 3. CRÉATION DES TABLES 

-- Table 1 : UTILISATEUR
CREATE TABLE UTILISATEUR (
    NumU INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Prenom VARCHAR(100) NOT NULL,
    Email VARCHAR(191) NOT NULL UNIQUE, -- Limité à 191 pour l'encodage utf8mb4 (Évite l'erreur #1071)
    Role VARCHAR(50) DEFAULT 'client',
    MotDePasse VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

-- Table 2 : CATEGORIE
CREATE TABLE CATEGORIE (
    NumCat INT AUTO_INCREMENT PRIMARY KEY,
    NomCat VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

-- Table 3 : PRODUIT (Appartient à une Catégorie, Vendu par un Utilisateur)
CREATE TABLE PRODUIT (
    NumProd INT AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR(255) NOT NULL,
    Etat VARCHAR(50),
    TypeTransaction VARCHAR(50) NOT NULL, -- Ex: 'achat', 'enchere', 'nego'
    PrixBase DECIMAL(10,2) NOT NULL,
    NumCat INT NOT NULL,
    NumU_Vendeur INT NOT NULL,
    FOREIGN KEY (NumCat) REFERENCES CATEGORIE(NumCat) ON DELETE RESTRICT,
    FOREIGN KEY (NumU_Vendeur) REFERENCES UTILISATEUR(NumU) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 4 : COMMANDE (Passée par un Utilisateur acheteur)
CREATE TABLE COMMANDE (
    NumCmd INT AUTO_INCREMENT PRIMARY KEY,
    DateCmd DATETIME DEFAULT CURRENT_TIMESTAMP,
    MontantTotal DECIMAL(10,2) NOT NULL,
    NumU_Acheteur INT NOT NULL,
    FOREIGN KEY (NumU_Acheteur) REFERENCES UTILISATEUR(NumU) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 5 : CONTIENT (Table de jointure issue de l'association Contient entre Commande et Produit)
CREATE TABLE CONTIENT (
    NumCmd INT NOT NULL,
    NumProd INT NOT NULL,
    Quantite INT NOT NULL DEFAULT 1,
    PrixUnit DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (NumCmd, NumProd), -- Clé primaire composite
    FOREIGN KEY (NumCmd) REFERENCES COMMANDE(NumCmd) ON DELETE CASCADE,
    FOREIGN KEY (NumProd) REFERENCES PRODUIT(NumProd) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 6 : ENCHERE (Liée à un Produit spécifique)
CREATE TABLE ENCHERE (
    NumEnchere INT AUTO_INCREMENT PRIMARY KEY,
    DateFin DATETIME NOT NULL,
    PrixActuel DECIMAL(10,2) NOT NULL,
    NumProd INT NOT NULL,
    FOREIGN KEY (NumProd) REFERENCES PRODUIT(NumProd) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 7 : OFFRE (Faite par un Utilisateur sur une Enchère en cours)
CREATE TABLE OFFRE (
    NumOffre INT AUTO_INCREMENT PRIMARY KEY,
    Montant DECIMAL(10,2) NOT NULL,
    DateOffre DATETIME DEFAULT CURRENT_TIMESTAMP,
    NumU_Acheteur INT NOT NULL,
    NumEnchere INT NOT NULL,
    FOREIGN KEY (NumU_Acheteur) REFERENCES UTILISATEUR(NumU) ON DELETE CASCADE,
    FOREIGN KEY (NumEnchere) REFERENCES ENCHERE(NumEnchere) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 8 : NEGOCIATION (Initiée par un Acheteur potentiel pour un Produit)
CREATE TABLE NEGOCIATION (
    NumNego INT AUTO_INCREMENT PRIMARY KEY,
    Statut VARCHAR(50) DEFAULT 'en_cours',
    NumU_Acheteur INT NOT NULL,
    NumProd INT NOT NULL,
    FOREIGN KEY (NumU_Acheteur) REFERENCES UTILISATEUR(NumU) ON DELETE CASCADE,
    FOREIGN KEY (NumProd) REFERENCES PRODUIT(NumProd) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Table 9 : MESSAGE_NEGO (Messages échangés au sein d'une Négociation)
CREATE TABLE MESSAGE_NEGO (
    NumMsg INT AUTO_INCREMENT PRIMARY KEY,
    Contenu TEXT NOT NULL,
    DateMsg DATETIME DEFAULT CURRENT_TIMESTAMP,
    MontantProp DECIMAL(10,2), -- Peut être NULL si le message ne contient pas d'offre chiffrée
    NumNego INT NOT NULL,
    NumU_Expediteur INT NOT NULL,
    FOREIGN KEY (NumNego) REFERENCES NEGOCIATION(NumNego) ON DELETE CASCADE,
    FOREIGN KEY (NumU_Expediteur) REFERENCES UTILISATEUR(NumU) ON DELETE CASCADE
) ENGINE=InnoDB;